=== AndriiIakubovych/Training/WPF/Lesson 03/Task 2/CompanyEmployeesOperating/bin/Release/company.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:simpleType name="genderType">
    <xs:restriction base="xs:string">
      <xs:pattern value="Мужской|Женский"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="departmentType">
    <xs:sequence>
      <xs:element name="department" type="xs:string" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
  <xs:simpleType name="salaryType">
    <xs:restriction base="xs:float">
      <xs:minExclusive value="1"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:element name="data">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="employees">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="employee" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="lname" type="xs:string"/>
                    <xs:element name="fname" type="xs:string"/>
                    <xs:element name="mname" type="xs:string"/>
                    <xs:element name="photo" type="xs:string" minOccurs="0"/>
                    <xs:element name="birthdate" type="xs:date"/>
                    <xs:element name="gender" type="genderType"/>
                    <xs:element name="address" type="xs:string" minOccurs="0"/>
                    <xs:element name="telephone" type="xs:string" minOccurs="0"/>
                    <xs:element name="department" type="xs:string"/>
                    <xs:element name="position" type="xs:string"/>
                    <xs:element name="salary" type="salaryType" minOccurs="0"/>
                    <xs:element name="contract" type="xs:string" minOccurs="0"/>
                    <xs:element name="hiredate" type="xs:date"/>
                    <xs:element name="information" type="xs:string" minOccurs="0"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="departments" type="departmentType"/>
      </xs:sequence>
    </xs:complexType>
    <xs:key name="departmentId">
      <xs:selector xpath="./departments/department"/>
      <xs:field xpath="."/>
    </xs:key>
    <xs:keyref name="referenceDepartmentId" refer="departmentId">
      <xs:selector xpath="./employees/employee/department"/>
      <xs:field xpath="."/>
    </xs:keyref>
  </xs:element>
</xs:schema>

=== AndriiIakubovych/Training/WPF/Lesson 3/Task 2/CompanyEmployeesOperating/bin/Release/company.xml
<?xml version="1.0" encoding="utf-8"?>
<data xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="company.xsd">
  <employees>
    <employee>
      <lname>Гаврилов</lname>
      <fname>Владимир</fname>
      <mname>Петрович</mname>
      <photo>employee-2.png</photo>
      <birthdate>1968-07-03</birthdate>
      <gender>Мужской</gender>
      <address>ул. Мироносицкая, 3, кв. 21</address>
      <telephone>+38 (095) 276-11-08</telephone>
      <department>Системный анализ</department>
      <position>Старший системный аналитик</position>
      <salary>28000</salary>
      <contract>№БА0000028</contract>
      <hiredate>2016-11-12</hiredate>
      <information>Окончил Харьковский Политехнический Институт по специальности "Ядерная физика" в 1993 г. Гражданин Украины, проживает в г. Харьков. Имеет более 15-ти лет опыта работы системным аналитиком. Электронный адрес: gavrilov.viktor@gmail.com.</information>
    </employee>
    <employee>
      <lname>Иванов</lname>
      <fname>Павел</fname>
      <mname>Васильевич</mname>
      <photo>employee-1.png</photo>
      <birthdate>1985-12-10</birthdate>
      <gender>Мужской</gender>
      <address>ул. Клочковская, 183, кв. 95</address>
      <telephone>+38 (067) 643-23-19</telephone>
      <department>Информационные технологии</department>
      <position>Инженер-программист</position>
      <salary>15000</salary>
      <contract>№БА0000027</contract>
      <hiredate>2017-06-01</hiredate>
      <information>Окончил Харьковский Институт Радио Электроники по специальности "Программирование и алгоритмические языки" в 2007 г. Гражданин Украины, проживает в г. Харьков. Опыт работы: 10 лет. Skype: Ivanov1985.</information>
    </employee>
    <employee>
      <lname>Резникова</lname>
      <fname>Анна</fname>
      <mname>Алексеевна</mname>
      <photo>employee-5.png</photo>
      <birthdate>1988-11-10</birthdate>
      <gender>Женский</gender>
      <address>ул. Новгородская, 32, кв. 4</address>
      <telephone>+38 (095) 631-99-17</telephone>
      <department>Бухгалтерия</department>
      <position>Помощник бухгалтера</position>
      <salary>12000</salary>
      <contract>№БА0000013</contract>
      <hiredate>2015-05-13</hiredate>
      <information>Окончила Харьковский Национальный Экономический университет по специальности "Банковское дело" в 2011 г. Гражданинка Украины, проживает в г. Харьков.</information>
    </employee>
    <employee>
      <lname>Игнатенко</lname>
      <fname>Кирилл</fname>
      <mname>Николаевич</mname>
      <birthdate>1991-08-22</birthdate>
      <gender>Мужской</gender>
      <address>ул. Космическая, 134, кв. 89</address>
      <telephone>+38 (067) 437-61-02</telephone>
      <department>Информационные технологии</department>
      <position>Инженер-программист</position>
      <salary>15000</salary>
      <contract>№БА0000022</contract>
      <hiredate>2016-03-26</hiredate>
    </employee>
    <employee>
      <lname>Коваленко</lname>
      <fname>Елена</fname>
      <mname>Степановна</mname>
      <photo>employee-4.png</photo>
      <birthdate>1987-05-16</birthdate>
      <gender>Женский</gender>
      <address>пр. Победы, 167А, кв. 153</address>
      <telephone>+38 (098) 345-82-10</telephone>
      <department>Отдел кадров</department>
      <position>Менеджер по подбору персонала</position>
      <salary>12000</salary>
      <contract>№БА0000021</contract>
      <hiredate>2011-05-28</hiredate>
      <information>Окончила Харьковский Национальный Университет им. Каразина по специальности "Международные экономические отношения" в 2009 г. Гражданинка Украины, проживает в г. Харьков. Опыт работы HR: 6 лет.</information>
    </employee>
    <employee>
      <lname>Долгарева</lname>
      <fname>Ирина</fname>
      <mname>Владимировна</mname>
      <photo>employee-3.png</photo>
      <birthdate>1973-02-19</birthdate>
      <gender>Женский</gender>
      <address>ул. Карла Маркса, 24, кв. 92</address>
      <telephone>+38 (067) 893-26-71</telephone>
      <department>Бухгалтерия</department>
      <position>Главный бухгалтер</position>
      <salary>20000</salary>
      <contract>№БА0000026</contract>
      <hiredate>2012-04-13</hiredate>
      <information>Окончила Харьковский Национальный Университет им. Каразина по специальности "Бухгалтерский учёт" в 1986 г. Гражданка Украины, проживает в г. Харьков. Электронный адрес: dolgareva.irina@gmail.com.</information>
    </employee>
    <employee>
      <lname>Баринов</lname>
      <fname>Андрей</fname>
      <mname>Вячеславович</mname>
      <photo>employee-6.png</photo>
      <birthdate>1983-10-21</birthdate>
      <gender>Мужской</gender>
      <address>пр. Героев Сталинграда, 184, кв. 82</address>
      <telephone>+38 (067) 983-17-44</telephone>
      <department>Информационные технологии</department>
      <position>Сетевой инженер</position>
      <salary>23000</salary>
      <contract>№БА0000029</contract>
      <hiredate>2010-05-13</hiredate>
      <information>Окончил Харьковский Политехнический Институт по специальности "Экономика и право" в 2005 г. Гражданин Украины, проживает в г. Харьков. Электронный адрес: pribilov.andrii@gmail.com.</information>
    </employee>
    <employee>
      <lname>Яковенко</lname>
      <fname>Олег</fname>
      <mname>Фёдорович</mname>
      <photo>employee-7.png</photo>
      <birthdate>1989-06-02</birthdate>
      <gender>Мужской</gender>
      <address>ул. Спортивная, 42, кв. 90</address>
      <telephone>+38 (973) 426-01-15</telephone>
      <department>Информационные технологии</department>
      <position>Системный администратор</position>
      <salary>13000</salary>
      <contract>№БА0000010</contract>
      <hiredate>2017-09-23</hiredate>
      <information>Окончил Компьютерную Академию "ШАГ" по специальности "Администрирование компьютерных систем" в 2012 г. Гражданин Украины, проживает в г. Харьков. Опыт работы: 3 года. Skype: Yakovenko1989.</information>
    </employee>
  </employees>
  <departments>
    <department>Отдел кадров</department>
    <department>Информационные технологии</department>
    <department>Бухгалтерия</department>
    <department>Системный анализ</department>
  </departments>
</data>
