=== AndriiIakubovych/Training/EPAM Systems/Lesson 4/FootballGameModel/bin/Debug/football.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="membership">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="teams">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="team" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="players">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="player" minOccurs="11" maxOccurs="11">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="name" type="xs:string"/>
                                <xs:element name="age" type="xs:integer"/>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>                         
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="coach" type="xs:string"/>                    
                  </xs:sequence>
                  <xs:attribute name="name" type="xs:string" use="required"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="referees">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="referee" type="xs:string" maxOccurs="unbounded"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>      
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== AndriiIakubovych/Training/EPAM Systems/Lesson 04/FootballGameModel/bin/Debug/football.xml
<?xml version="1.0" encoding="utf-8"?>
<membership xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="football.xsd">
  <teams>
    <team name="Barcelona">
      <players>
        <player>
          <name>Adriano</name>
          <age>33</age>
        </player>
        <player>
          <name>David Villa</name>
          <age>36</age>
        </player>
        <player>
          <name>Javier Mascherano</name>
          <age>33</age>
        </player>
        <player>
          <name>Jordi Alba</name>
          <age>28</age>
        </player>
        <player>
          <name>Sergio Busquets</name>
          <age>29</age>
        </player>
        <player>
          <name>Seydou Keita</name>
          <age>37</age>
        </player>
        <player>
          <name>Dani Alves</name>
          <age>34</age>
        </player>
        <player>
          <name>Eric Abidal</name>
          <age>38</age>
        </player>
        <player>
          <name>Yaya Toure</name>
          <age>34</age>
        </player>
        <player>
          <name>Gerard Pique</name>
          <age>30</age>
        </player>
        <player>
          <name>Ivan Rakitic</name>
          <age>29</age>
        </player>
      </players>
      <coach>Ernesto Valverde</coach>
    </team>
    <team name="Manchester United">
      <players>
        <player>
          <name>Anthony Martial</name>
          <age>21</age>
        </player>
        <player>
          <name>Ander Herrera</name>
          <age>28</age>
        </player>
        <player>
          <name>Jesse Lingard</name>
          <age>24</age>
        </player>
        <player>
          <name>Daley Blind</name>
          <age>27</age>
        </player>
        <player>
          <name>Juan Mata</name>
          <age>29</age>
        </player>
        <player>
          <name>Marouane Fellaini</name>
          <age>30</age>
        </player>
        <player>
          <name>Robin van Persie</name>
          <age>34</age>
        </player>
        <player>
          <name>Ashley Young</name>
          <age>32</age>
        </player>
        <player>
          <name>Phil Jones</name>
          <age>25</age>
        </player>
        <player>
          <name>David de Gea</name>
          <age>27</age>
        </player>
        <player>
          <name>Chris Smalling</name>
          <age>28</age>
        </player>
      </players>
      <coach>Jose Mourinho</coach>
    </team>  
    <team name="Milan">
      <players>
        <player>
          <name>Giacomo Bonaventura</name>
          <age>28</age>
        </player>
        <player>
          <name>Andrea Poli</name>
          <age>28</age>
        </player>
        <player>
          <name>Cristian Zapata</name>
          <age>31</age>
        </player>
        <player>
          <name>Riccardo Montolivo</name>
          <age>32</age>
        </player>
        <player>
          <name>Mattia De Sciglio</name>
          <age>25</age>
        </player>
        <player>
          <name>Marouane Fellaini</name>
          <age>30</age>
        </player>
        <player>
          <name>Stephan El Shaarawy</name>
          <age>25</age>
        </player>
        <player>
          <name>Philippe Mexes</name>
          <age>35</age>
        </player>
        <player>
          <name>Urby Emanuelson</name>
          <age>31</age>
        </player>
        <player>
          <name>Robinho</name>
          <age>33</age>
        </player>
        <player>
          <name>Kevin-Prince Boateng</name>
          <age>30</age>
        </player>
      </players>
      <coach>Vincenzo Montella</coach>
    </team>
  </teams>
  <referees>
    <referee>Gerald Lehner</referee>
    <referee>Serge Gumienny</referee>
    <referee>Renato Marsiglia</referee>
    <referee>David Gantar</referee>
  </referees>
</membership>
